copy missing file

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -65,6 +65,12 @@ jobs:
             full_tag="${tag}-${version}"
             echo "Full tag is: $full_tag ."
 
+            cp "$INSTALL_COMPOSER" "./$dir/"
+            if [[ $? -ne 0 ]]; then
+              echo "Error copying $INSTALL_COMPOSER to $dir"
+              exit 1
+            fi
+
             # Check if there were changes in the directory
             #if git diff --name-only HEAD^ HEAD | grep -q "$dir/"; then
               # Build the Docker image and push to both Docker Hub and GHCR
